use crate::parser::ast::*;
use anyhow::Result;
use std::collections::HashMap;

/// Java type used for Roze's "no annotation given" / dynamic-ish values.
const OBJECT_TYPE: &str = "Object";

/// Returns the Java return type for a built-in Core (string/math)
/// intrinsic, or None if `name` isn't one. Keep this in sync with
/// `semantic::builtin_signatures`.
fn intrinsic_return_type(name: &str) -> Option<&'static str> {
    match name {
        "string_length" => Some("int"),
        "string_concat" => Some("String"),
        "string_to_upper" => Some("String"),
        "string_to_lower" => Some("String"),
        "abs" => Some("int"),
        "max" => Some("int"),
        "min" => Some("int"),
        "to_string" => Some("String"),
        "to_int" => Some("int"),
        "is_number" => Some("boolean"),
        "is_string" => Some("boolean"),
        _ => None,
    }
}

fn is_intrinsic(name: &str) -> bool {
    intrinsic_return_type(name).is_some()
}

/// Maps a Roze source-level type annotation to a Java type name.
/// `default_java` is used when no annotation was given at all (distinct
/// from an annotation the compiler doesn't recognize, which still maps to
/// Object).
fn roze_type_to_java(type_name: Option<&str>, default_java: &str) -> String {
    match type_name {
        Some("int") => "int".to_string(),
        Some("string") => "String".to_string(),
        Some("bool") => "boolean".to_string(),
        Some("void") => "void".to_string(),
        Some(_) => OBJECT_TYPE.to_string(),
        None => default_java.to_string(),
    }
}

/// name -> java type, for locals/params visible at the current point in
/// generation. A `Vec` of frames acts as a scope stack (innermost last).
type Scope = Vec<HashMap<String, String>>;

pub struct JavaSourceGenerator {
    program: Program,
    class_name: String,
    /// name -> (java param types, java return type) for every user-defined
    /// top-level function, so call sites and `let` type inference never
    /// have to guess.
    functions: HashMap<String, (Vec<String>, String)>,
}

impl JavaSourceGenerator {
    pub fn new(program: Program, class_name: String) -> Self {
        let mut functions = HashMap::new();
        for stmt in &program.statements {
            if let Statement::Function { name, params, return_type, .. } = stmt {
                let param_types: Vec<String> = params.iter()
                    .map(|p| roze_type_to_java(p.type_name.as_deref(), OBJECT_TYPE))
                    .collect();
                let ret = roze_type_to_java(return_type.as_deref(), "void");
                functions.insert(name.clone(), (param_types, ret));
            }
        }
        Self { program, class_name, functions }
    }

    pub fn generate(&self) -> Result<String> {
        let mut source = String::new();
        source.push_str("// Generated by Roze compiler v0.1\n");
        source.push_str(&format!("public class {} {{\n", self.class_name));

        let mut main_found = false;
        for stmt in &self.program.statements {
            if let Statement::Function { name, params, body, .. } = stmt {
                // Core intrinsics are handled entirely at each call site
                // (see generate_call) and never emitted as a real method,
                // even if a same-named function happens to be declared.
                if is_intrinsic(name) {
                    continue;
                }

                if name == "main" {
                    source.push_str("    public static void main(String[] args) {\n");
                    let mut scope: Scope = vec![HashMap::new()];
                    self.generate_statement(&mut source, body, 2, &mut scope)?;
                    source.push_str("    }\n");
                    main_found = true;
                } else {
                    let (param_types, ret_java) = self.functions.get(name).cloned().unwrap_or_default();
                    let params_sig: Vec<String> = params.iter().zip(param_types.iter())
                        .map(|(p, t)| format!("{} {}", t, p.name))
                        .collect();

                    source.push_str(&format!(
                        "    public static {} {}({}) {{\n",
                        ret_java, name, params_sig.join(", ")
                    ));

                    let mut scope: Scope = vec![HashMap::new()];
                    {
                        let frame = scope.last_mut().expect("scope always has a frame");
                        for (p, t) in params.iter().zip(param_types.iter()) {
                            frame.insert(p.name.clone(), t.clone());
                        }
                    }
                    self.generate_statement(&mut source, body, 2, &mut scope)?;
                    source.push_str("    }\n");
                }
            }
        }

        if !main_found {
            source.push_str("    public static void main(String[] args) {\n");
            source.push_str("        System.out.println(\"No main function found!\");\n");
            source.push_str("    }\n");
        }

        source.push_str("}\n");

        Ok(source)
    }

    fn generate_statement(&self, source: &mut String, stmt: &Statement, indent: usize, scope: &mut Scope) -> Result<()> {
        let indent_str = "    ".repeat(indent);

        match stmt {
            Statement::Block { statements, .. } => {
                for stmt in statements {
                    self.generate_statement(source, stmt, indent, scope)?;
                }
            }
            Statement::Expression { expr, .. } => {
                if let Expression::Call { function, arguments, .. } = expr.as_ref() {
                    if let Expression::Identifier { name, .. } = function.as_ref() {
                        if name == "println" {
                            source.push_str(&format!("{}System.out.println(", indent_str));
                            self.generate_println_args(source, arguments, scope)?;
                            source.push_str(");\n");
                            return Ok(());
                        }
                    }
                }
                source.push_str(&indent_str);
                self.generate_expression(source, expr, scope)?;
                source.push_str(";\n");
            }
            Statement::Let { name, value, .. } => {
                let java_type = self.infer_type(value, scope);

                source.push_str(&format!("{}{} {} = ", indent_str, java_type, name));
                self.generate_expression(source, value, scope)?;
                source.push_str(";\n");

                scope.last_mut().expect("scope always has a frame").insert(name.clone(), java_type);
            }
            Statement::Return { value, .. } => {
                if let Some(expr) = value {
                    source.push_str(&format!("{}return ", indent_str));
                    self.generate_expression(source, expr, scope)?;
                    source.push_str(";\n");
                } else {
                    source.push_str(&format!("{}return;\n", indent_str));
                }
            }
            Statement::Function { .. } => {
                // Nested function declarations aren't supported; top-level
                // functions are collected and emitted directly in `generate`.
            }
            Statement::Import { .. } => {
                // No module system yet -- see ROADMAP.
            }
            Statement::Assign { name, value, .. } => {
                source.push_str(&format!("{}{} = ", indent_str, name));
                self.generate_expression(source, value, scope)?;
                source.push_str(";\n");
            }
            Statement::If { condition, then_branch, else_branch, .. } => {
                self.generate_if_chain(source, condition, then_branch, else_branch.as_deref(), indent, scope, true)?;
            }
            Statement::While { condition, body, .. } => {
                source.push_str(&format!("{}while (", indent_str));
                self.generate_expression(source, condition, scope)?;
                source.push_str(") {\n");
                scope.push(HashMap::new());
                self.generate_statement(source, body, indent + 1, scope)?;
                scope.pop();
                source.push_str(&format!("{}}}\n", indent_str));
            }
        }

        Ok(())
    }

    /// Emits `if (cond) { ... }`, followed by any `else` / `else if` chain,
    /// ending with exactly one trailing newline.
    fn generate_if_chain(
        &self,
        source: &mut String,
        condition: &Expression,
        then_branch: &Statement,
        else_branch: Option<&Statement>,
        indent: usize,
        scope: &mut Scope,
        write_indent: bool,
    ) -> Result<()> {
        let indent_str = "    ".repeat(indent);

        if write_indent {
            source.push_str(&indent_str);
        }
        source.push_str("if (");
        self.generate_expression(source, condition, scope)?;
        source.push_str(") {\n");
        scope.push(HashMap::new());
        self.generate_statement(source, then_branch, indent + 1, scope)?;
        scope.pop();
        source.push_str(&format!("{}}}", indent_str));

        match else_branch {
            None => source.push('\n'),
            Some(Statement::If { condition, then_branch, else_branch, .. }) => {
                source.push_str(" else ");
                self.generate_if_chain(source, condition, then_branch, else_branch.as_deref(), indent, scope, false)?;
            }
            Some(other) => {
                source.push_str(" else {\n");
                scope.push(HashMap::new());
                self.generate_statement(source, other, indent + 1, scope)?;
                scope.pop();
                source.push_str(&format!("{}}}\n", indent_str));
            }
        }

        Ok(())
    }

    fn generate_println_args(&self, source: &mut String, arguments: &[Expression], scope: &Scope) -> Result<()> {
        if arguments.is_empty() {
            return Ok(());
        }
        if arguments.len() == 1 {
            return self.generate_expression(source, &arguments[0], scope);
        }
        // println with several arguments concatenates them, so
        // `println(a, b)` behaves like `println(a + b)`.
        source.push('(');
        for (i, arg) in arguments.iter().enumerate() {
            if i > 0 {
                source.push_str(" + ");
            }
            self.generate_expression(source, arg, scope)?;
        }
        source.push(')');
        Ok(())
    }

    /// Infers the Java type an expression will evaluate to, using tracked
    /// local/parameter types instead of guessing from variable names.
    fn infer_type(&self, expr: &Expression, scope: &Scope) -> String {
        match expr {
            Expression::Number { .. } => "int".to_string(),
            Expression::String { .. } => "String".to_string(),
            Expression::Boolean { .. } => "boolean".to_string(),
            Expression::Null { .. } => OBJECT_TYPE.to_string(),
            Expression::Identifier { name, .. } => {
                for frame in scope.iter().rev() {
                    if let Some(t) = frame.get(name) {
                        return t.clone();
                    }
                }
                OBJECT_TYPE.to_string()
            }
            Expression::Unary { operand, .. } => self.infer_type(operand, scope),
            Expression::Binary { left, operator, right, .. } => {
                let left_type = self.infer_type(left, scope);
                let right_type = self.infer_type(right, scope);

                match operator {
                    BinaryOperator::Add => {
                        if left_type == "String" || right_type == "String" {
                            "String".to_string()
                        } else if left_type == "int" && right_type == "int" {
                            "int".to_string()
                        } else {
                            // One side is some Object-typed/unknown value;
                            // Java's `+` between an Object and anything
                            // else always means string concatenation, so
                            // this is the only type that's always valid.
                            "String".to_string()
                        }
                    }
                    BinaryOperator::Subtract | BinaryOperator::Multiply | BinaryOperator::Divide => "int".to_string(),
                    BinaryOperator::Equal | BinaryOperator::NotEqual |
                    BinaryOperator::LessThan | BinaryOperator::GreaterThan |
                    BinaryOperator::LessEqual | BinaryOperator::GreaterEqual |
                    BinaryOperator::And | BinaryOperator::Or => "boolean".to_string(),
                }
            }
            Expression::Call { function, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    if name == "println" {
                        return "void".to_string();
                    }
                    if let Some(ret) = intrinsic_return_type(name) {
                        return ret.to_string();
                    }
                    if let Some((_, ret)) = self.functions.get(name) {
                        return ret.clone();
                    }
                }
                OBJECT_TYPE.to_string()
            }
        }
    }

    fn generate_expression(&self, source: &mut String, expr: &Expression, scope: &Scope) -> Result<()> {
        match expr {
            Expression::String { value, .. } => {
                let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
                source.push_str(&format!("\"{}\"", escaped));
            }
            Expression::Number { value, .. } => {
                source.push_str(value);
            }
            Expression::Identifier { name, .. } => {
                source.push_str(name);
            }
            Expression::Boolean { value, .. } => {
                source.push_str(&format!("{}", value));
            }
            Expression::Null { .. } => {
                source.push_str("null");
            }
            Expression::Call { function, arguments, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    self.generate_call(source, name, arguments, scope)?;
                }
            }
            Expression::Binary { left, operator, right, .. } => {
                let left_type = self.infer_type(left, scope);
                let right_type = self.infer_type(right, scope);
                let is_string_concat = matches!(operator, BinaryOperator::Add)
                    && (left_type == "String" || right_type == "String");

                source.push('(');
                self.generate_expression(source, left, scope)?;
                if is_string_concat {
                    source.push_str(" + ");
                } else {
                    let op = match operator {
                        BinaryOperator::Add => " + ",
                        BinaryOperator::Subtract => " - ",
                        BinaryOperator::Multiply => " * ",
                        BinaryOperator::Divide => " / ",
                        BinaryOperator::Equal => " == ",
                        BinaryOperator::NotEqual => " != ",
                        BinaryOperator::LessThan => " < ",
                        BinaryOperator::GreaterThan => " > ",
                        BinaryOperator::LessEqual => " <= ",
                        BinaryOperator::GreaterEqual => " >= ",
                        BinaryOperator::And => " && ",
                        BinaryOperator::Or => " || ",
                    };
                    source.push_str(op);
                }
                self.generate_expression(source, right, scope)?;
                source.push(')');
            }
            Expression::Unary { operator, operand, .. } => {
                let op = match operator {
                    UnaryOperator::Negate => "-",
                    UnaryOperator::Not => "!",
                };
                source.push_str(op);
                self.generate_expression(source, operand, scope)?;
            }
        }

        Ok(())
    }

    /// Generates a call, rewriting Core (string/math) intrinsics to real
    /// JVM standard-library calls, since Roze has no method-call syntax of
    /// its own yet to express `s.length()` directly.
    fn generate_call(&self, source: &mut String, name: &str, arguments: &[Expression], scope: &Scope) -> Result<()> {
        match name {
            "string_length" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).length()");
            }
            "string_to_upper" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).toUpperCase()");
            }
            "string_to_lower" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).toLowerCase()");
            }
            "string_concat" if arguments.len() == 2 => {
                source.push('(');
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(" + ");
                self.generate_expression(source, &arguments[1], scope)?;
                source.push(')');
            }
            "abs" if arguments.len() == 1 => {
                source.push_str("Math.abs(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push(')');
            }
            "max" if arguments.len() == 2 => {
                source.push_str("Math.max(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push_str(", ");
                self.generate_int_arg(source, &arguments[1], scope)?;
                source.push(')');
            }
            "min" if arguments.len() == 2 => {
                source.push_str("Math.min(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push_str(", ");
                self.generate_int_arg(source, &arguments[1], scope)?;
                source.push(')');
            }
            "to_string" if arguments.len() == 1 => {
                source.push_str("String.valueOf(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push(')');
            }
            "to_int" if arguments.len() == 1 => {
                source.push_str("Integer.parseInt(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push(')');
            }
            "is_number" if arguments.len() == 1 => {
                source.push_str("((Object)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(") instanceof Integer)");
            }
            "is_string" if arguments.len() == 1 => {
                source.push_str("((Object)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(") instanceof String)");
            }
            "println" => {
                source.push_str("System.out.println(");
                self.generate_println_args(source, arguments, scope)?;
                source.push(')');
            }
            _ => {
                source.push_str(name);
                source.push('(');
                for (i, arg) in arguments.iter().enumerate() {
                    if i > 0 {
                        source.push_str(", ");
                    }
                    self.generate_expression(source, arg, scope)?;
                }
                source.push(')');
            }
        }
        Ok(())
    }

    /// Generates an expression known to be used in an `int`-typed position
    /// (a Math.* argument). If the expression's static type isn't already
    /// `int`, it's coming from an Object-typed (untyped-parameter) value,
    /// so we unbox it via Integer -- valid whenever the runtime value
    /// really is a boxed Integer, matching the declared `int` parameter.
    fn generate_int_arg(&self, source: &mut String, expr: &Expression, scope: &Scope) -> Result<()> {
        let t = self.infer_type(expr, scope);
        if t == "int" {
            self.generate_expression(source, expr, scope)
        } else {
            source.push_str("((Integer)(Object)(");
            self.generate_expression(source, expr, scope)?;
            source.push_str("))");
            Ok(())
        }
    }
}
