use crate::parser::ast::*;
use anyhow::Result;

pub struct JavaSourceGenerator {
    program: Program,
    class_name: String,
}

impl JavaSourceGenerator {
    pub fn new(program: Program, class_name: String) -> Self {
        Self { program, class_name }
    }

    pub fn generate(&self) -> Result<String> {
        let mut source = String::new();
        source.push_str(&format!("// Generated by Roze compiler v0.1\n"));
        source.push_str(&format!("public class {} {{\n", self.class_name));

        // Find the main function and generate it
        let mut main_found = false;
        for stmt in &self.program.statements {
            if let Statement::Function { name, params, body, .. } = stmt {
                if name == "main" {
                    // Generate main method with String[] args
                    source.push_str(&format!("    public static void main(String[] args) {{\n"));
                    self.generate_statement(&mut source, body, 2)?;
                    source.push_str(&format!("    }}\n"));
                    main_found = true;
                }
            }
        }

        // If no main function found, create a default one
        if !main_found {
            source.push_str(&format!("    public static void main(String[] args) {{\n"));
            source.push_str(&format!("        System.out.println(\"No main function found!\");\n"));
            source.push_str(&format!("    }}\n"));
        }

        source.push_str(&format!("}}\n"));

        Ok(source)
    }

    fn generate_statement(&self, source: &mut String, stmt: &Statement, indent: usize) -> Result<()> {
        let indent_str = "    ".repeat(indent);

        match stmt {
            Statement::Block { statements, .. } => {
                for stmt in statements {
                    self.generate_statement(source, stmt, indent)?;
                }
            }
            Statement::Expression { expr, .. } => {
                // Check if it's a println call
                if let Expression::Call { function, arguments, .. } = expr.as_ref() {
                    if let Expression::Identifier { name, .. } = function.as_ref() {
                        if name == "println" {
                            source.push_str(&format!("{}System.out.println(", indent_str));
                            for (i, arg) in arguments.iter().enumerate() {
                                if i > 0 {
                                    source.push_str(", ");
                                }
                                self.generate_expression(source, arg, indent)?;
                            }
                            source.push_str(&format!(");\n"));
                            return Ok(());
                        }
                    }
                }
                // Generic expression statement
                source.push_str(&format!("{}", indent_str));
                self.generate_expression(source, expr, indent)?;
                source.push_str(&format!(";\n"));
            }
            Statement::Let { name, value, .. } => {
                // INFER THE TYPE FROM THE VALUE
                let java_type = self.infer_type(value);

                source.push_str(&format!("{}{} {} = ", indent_str, java_type, name));
                self.generate_expression(source, value, indent)?;
                source.push_str(&format!(";\n"));
            }
            Statement::Return { value, .. } => {
                if let Some(expr) = value {
                    source.push_str(&format!("{}return ", indent_str));
                    self.generate_expression(source, expr, indent)?;
                    source.push_str(&format!(";\n"));
                } else {
                    source.push_str(&format!("{}return;\n", indent_str));
                }
            }
            Statement::Function { .. } => {
                // Skip nested functions for now
            }
            _ => {}
        }

        Ok(())
    }

    // Helper function to infer Java type from Roze expression
    fn infer_type(&self, expr: &Expression) -> String {
        match expr {
            Expression::Number { .. } => "int".to_string(),
            Expression::String { .. } => "String".to_string(),
            Expression::Boolean { .. } => "boolean".to_string(),
            Expression::Identifier { name, .. } => {
                // For now, we don't have type info, assume String
                // In a real compiler, we'd look up the variable in a symbol table
                // For this MVP, we'll check if it's a common numeric variable name
                if name == "x" || name == "y" || name == "z" || name == "i" || name == "j" || name == "k" {
                    "int".to_string()
                } else {
                    "String".to_string()
                }
            }
            Expression::Binary { left, operator, right, .. } => {
                // Check if it's string concatenation
                let left_type = self.infer_type(left);
                let right_type = self.infer_type(right);

                // If either side is a string, it's string concatenation
                if left_type == "String" || right_type == "String" {
                    return "String".to_string();
                }

                // If both are ints, it's an integer operation
                if left_type == "int" && right_type == "int" {
                    return "int".to_string();
                }

                // For numeric operations with mixed types, default to String
                // (in a real compiler we'd handle this with type coercion)
                match operator {
                    BinaryOperator::Add => {
                        // String concatenation if either side is String
                        if left_type == "String" || right_type == "String" {
                            "String".to_string()
                        } else {
                            "int".to_string()
                        }
                    }
                    BinaryOperator::Subtract | BinaryOperator::Multiply | BinaryOperator::Divide => {
                        // These operations are only for numbers
                        "int".to_string()
                    }
                    BinaryOperator::Equal | BinaryOperator::NotEqual |
                    BinaryOperator::LessThan | BinaryOperator::GreaterThan |
                    BinaryOperator::LessEqual | BinaryOperator::GreaterEqual |
                    BinaryOperator::And | BinaryOperator::Or => {
                        // Comparisons return boolean
                        "boolean".to_string()
                    }
                }
            }
            Expression::Call { function, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    if name == "println" {
                        // println returns void
                        "void".to_string()
                    } else {
                        // Unknown function, default to String
                        "String".to_string()
                    }
                } else {
                    "String".to_string()
                }
            }
            _ => "String".to_string(), // Default to String
        }
    }

    fn generate_expression(&self, source: &mut String, expr: &Expression, indent: usize) -> Result<()> {
        match expr {
            Expression::String { value, .. } => {
                let escaped = value.replace("\\", "\\\\").replace("\"", "\\\"");
                source.push_str(&format!("\"{}\"", escaped));
            }
            Expression::Number { value, .. } => {
                source.push_str(value);
            }
            Expression::Identifier { name, .. } => {
                source.push_str(name);
            }
            Expression::Boolean { value, .. } => {
                source.push_str(&format!("{}", value));
            }
            Expression::Null { .. } => {
                source.push_str("null");
            }
            Expression::Call { function, arguments, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    source.push_str(name);
                    source.push_str("(");
                    for (i, arg) in arguments.iter().enumerate() {
                        if i > 0 {
                            source.push_str(", ");
                        }
                        self.generate_expression(source, arg, indent)?;
                    }
                    source.push_str(")");
                }
            }
            Expression::Binary { left, operator, right, .. } => {
                // Check if it's string concatenation by checking types
                let left_is_string = match left.as_ref() {
                    Expression::String { .. } => true,
                    _ => false,
                };
                let right_is_string = match right.as_ref() {
                    Expression::String { .. } => true,
                    _ => false,
                };

                let is_string_concat = match operator {
                    BinaryOperator::Add => left_is_string || right_is_string,
                    _ => false,
                };

                if is_string_concat {
                    source.push_str("(");
                    self.generate_expression(source, left, indent)?;
                    source.push_str(" + ");
                    self.generate_expression(source, right, indent)?;
                    source.push_str(")");
                } else {
                    source.push_str("(");
                    self.generate_expression(source, left, indent)?;
                    let op = match operator {
                        BinaryOperator::Add => " + ",
                        BinaryOperator::Subtract => " - ",
                        BinaryOperator::Multiply => " * ",
                        BinaryOperator::Divide => " / ",
                        BinaryOperator::Equal => " == ",
                        BinaryOperator::NotEqual => " != ",
                        BinaryOperator::LessThan => " < ",
                        BinaryOperator::GreaterThan => " > ",
                        BinaryOperator::LessEqual => " <= ",
                        BinaryOperator::GreaterEqual => " >= ",
                        BinaryOperator::And => " && ",
                        BinaryOperator::Or => " || ",
                    };
                    source.push_str(op);
                    self.generate_expression(source, right, indent)?;
                    source.push_str(")");
                }
            }
            Expression::Unary { operator, operand, .. } => {
                let op = match operator {
                    UnaryOperator::Negate => "-",
                    UnaryOperator::Not => "!",
                };
                source.push_str(op);
                self.generate_expression(source, operand, indent)?;
            }
            _ => {}
        }

        Ok(())
    }
}