use crate::parser::ast::*;
use anyhow::Result;
use std::collections::HashMap;

/// Java type used for Roze's "no annotation given" / dynamic-ish values.
const OBJECT_TYPE: &str = "Object";

/// Returns the Java return type for a built-in Core (string/math)
/// intrinsic, or None if `name` isn't one. Keep this in sync with
/// `semantic::builtin_signatures`.
fn intrinsic_return_type(name: &str) -> Option<&'static str> {
    match name {
        "string_length" => Some("int"),
        "string_concat" => Some("String"),
        "string_to_upper" => Some("String"),
        "string_to_lower" => Some("String"),
        "abs" => Some("int"),
        "max" => Some("int"),
        "min" => Some("int"),
        "to_string" => Some("String"),
        "to_int" => Some("int"),
        "is_number" => Some("boolean"),
        "is_string" => Some("boolean"),
        _ => None,
    }
}

fn is_intrinsic(name: &str) -> bool {
    intrinsic_return_type(name).is_some()
}

/// Maps a Roze source-level type annotation to a Java type name.
/// `default_java` is used when no annotation was given at all (distinct
/// from an annotation the compiler doesn't recognize, which still maps to
/// Object).
fn roze_type_to_java(type_name: Option<&str>, default_java: &str) -> String {
    match type_name {
        Some("int") => "int".to_string(),
        Some("string") => "String".to_string(),
        Some("bool") => "boolean".to_string(),
        Some("void") => "void".to_string(),
        Some(_) => OBJECT_TYPE.to_string(),
        None => default_java.to_string(),
    }
}

/// name -> java type, for locals/params visible at the current point in
/// generation. A `Vec` of frames acts as a scope stack (innermost last).
type Scope = Vec<HashMap<String, String>>;

pub struct JavaSourceGenerator {
    program: Program,
    class_name: String,
    /// name -> (java param types, java return type) for every user-defined
    /// top-level function, so call sites and `let` type inference never
    /// have to guess.
    functions: HashMap<String, (Vec<String>, String)>,
}

impl JavaSourceGenerator {
    pub fn new(program: Program, class_name: String) -> Self {
        let mut functions = HashMap::new();
        for stmt in &program.statements {
            if let Statement::Function { name, params, return_type, .. } = stmt {
                let param_types: Vec<String> = params.iter()
                    .map(|p| roze_type_to_java(p.type_name.as_deref(), OBJECT_TYPE))
                    .collect();
                let ret = roze_type_to_java(return_type.as_deref(), "void");
                functions.insert(name.clone(), (param_types, ret));
            }
        }
        Self { program, class_name, functions }
    }

    pub fn generate(&self) -> Result<String> {
        let mut source = String::new();
        source.push_str("// Generated by Roze compiler v0.1\n");
        source.push_str(&format!("public class {} {{\n", self.class_name));

        let mut main_found = false;
        for stmt in &self.program.statements {
            if let Statement::Function { name, params, body, .. } = stmt {
                // Core intrinsics are handled entirely at each call site
                // (see generate_call) and never emitted as a real method,
                // even if a same-named function happens to be declared.
                if is_intrinsic(name) {
                    continue;
                }

                if name == "main" {
                    source.push_str("    public static void main(String[] args) {\n");
                    let mut scope: Scope = vec![HashMap::new()];
                    self.generate_statement(&mut source, body, 2, &mut scope)?;
                    source.push_str("    }\n");
                    main_found = true;
                } else {
                    let (param_types, ret_java) = self.functions.get(name).cloned().unwrap_or_default();
                    let params_sig: Vec<String> = params.iter().zip(param_types.iter())
                        .map(|(p, t)| format!("{} {}", t, p.name))
                        .collect();

                    source.push_str(&format!(
                        "    public static {} {}({}) {{\n",
                        ret_java, name, params_sig.join(", ")
                    ));

                    let mut scope: Scope = vec![HashMap::new()];
                    {
                        let frame = scope.last_mut().expect("scope always has a frame");
                        for (p, t) in params.iter().zip(param_types.iter()) {
                            frame.insert(p.name.clone(), t.clone());
                        }
                    }
                    self.generate_statement(&mut source, body, 2, &mut scope)?;
                    source.push_str("    }\n");
                }
            }
        }

        if !main_found {
            source.push_str("    public static void main(String[] args) {\n");
            source.push_str("        System.out.println(\"No main function found!\");\n");
            source.push_str("    }\n");
        }

        source.push_str("}\n");

        Ok(source)
    }

    fn generate_statement(&self, source: &mut String, stmt: &Statement, indent: usize, scope: &mut Scope) -> Result<()> {
        let indent_str = "    ".repeat(indent);

        match stmt {
            Statement::Block { statements, .. } => {
                for stmt in statements {
                    self.generate_statement(source, stmt, indent, scope)?;
                }
            }
            Statement::Expression { expr, .. } => {
                if let Expression::Call { function, arguments, .. } = expr.as_ref() {
                    if let Expression::Identifier { name, .. } = function.as_ref() {
                        if name == "println" {
                            source.push_str(&format!("{}System.out.println(", indent_str));
                            self.generate_println_args(source, arguments, scope)?;
                            source.push_str(");\n");
                            return Ok(());
                        }
                    }
                }
                source.push_str(&indent_str);
                self.generate_expression(source, expr, scope)?;
                source.push_str(";\n");
            }
            Statement::Let { name, value, .. } => {
                let java_type = self.infer_type(value, scope);

                source.push_str(&format!("{}{} {} = ", indent_str, java_type, name));
                self.generate_expression(source, value, scope)?;
                source.push_str(";\n");

                scope.last_mut().expect("scope always has a frame").insert(name.clone(), java_type);
            }
            Statement::Return { value, .. } => {
                if let Some(expr) = value {
                    source.push_str(&format!("{}return ", indent_str));
                    self.generate_expression(source, expr, scope)?;
                    source.push_str(";\n");
                } else {
                    source.push_str(&format!("{}return;\n", indent_str));
                }
            }
            Statement::Function { .. } => {
                // Nested function declarations aren't supported; top-level
                // functions are collected and emitted directly in `generate`.
            }
            Statement::Import { .. } => {
                // Imports are already resolved into real functions before
                // this stage even runs (see imports::resolve_imports),
                // so in practice there's nothing left to do here -- this
                // arm only exists in case that ever changes.
            }
            Statement::Assign { name, value, .. } => {
                source.push_str(&format!("{}{} = ", indent_str, name));
                self.generate_expression(source, value, scope)?;
                source.push_str(";\n");
            }
            Statement::If { condition, then_branch, else_branch, .. } => {
                self.generate_if_chain(source, condition, then_branch, else_branch.as_deref(), indent, scope, true)?;
            }
            Statement::While { condition, body, .. } => {
                source.push_str(&format!("{}while (", indent_str));
                self.generate_expression(source, condition, scope)?;
                source.push_str(") {\n");
                scope.push(HashMap::new());
                self.generate_statement(source, body, indent + 1, scope)?;
                scope.pop();
                source.push_str(&format!("{}}}\n", indent_str));
            }
            Statement::For { init, condition, update, body, .. } => {
                source.push_str(&format!("{}for (", indent_str));
                scope.push(HashMap::new());
                self.generate_for_clause(source, init, scope)?;
                source.push_str("; ");
                self.generate_expression(source, condition, scope)?;
                source.push_str("; ");
                self.generate_for_clause(source, update, scope)?;
                source.push_str(") {\n");
                self.generate_statement(source, body, indent + 1, scope)?;
                scope.pop();
                source.push_str(&format!("{}}}\n", indent_str));
            }
        }

        Ok(())
    }

    /// Renders a for-loop's init or update clause inline inside the
    /// Java `for (...)` header -- i.e. like `generate_statement`'s
    /// `Let`/`Assign` cases, but without the indent prefix or trailing
    /// `;\n` those emit as full statements. The parser guarantees a
    /// for-loop's init/update are always `Let` or `Assign`.
    fn generate_for_clause(&self, source: &mut String, stmt: &Statement, scope: &mut Scope) -> Result<()> {
        match stmt {
            Statement::Let { name, value, .. } => {
                let java_type = self.infer_type(value, scope);
                source.push_str(&format!("{} {} = ", java_type, name));
                self.generate_expression(source, value, scope)?;
                scope.last_mut().expect("scope always has a frame").insert(name.clone(), java_type);
            }
            Statement::Assign { name, value, .. } => {
                source.push_str(&format!("{} = ", name));
                self.generate_expression(source, value, scope)?;
            }
            _ => unreachable!("for-loop init/update is always Let or Assign (enforced by the parser)"),
        }
        Ok(())
    }

    /// Emits `if (cond) { ... }`, followed by any `else` / `else if` chain,
    /// ending with exactly one trailing newline.
    fn generate_if_chain(
        &self,
        source: &mut String,
        condition: &Expression,
        then_branch: &Statement,
        else_branch: Option<&Statement>,
        indent: usize,
        scope: &mut Scope,
        write_indent: bool,
    ) -> Result<()> {
        let indent_str = "    ".repeat(indent);

        if write_indent {
            source.push_str(&indent_str);
        }
        source.push_str("if (");
        self.generate_expression(source, condition, scope)?;
        source.push_str(") {\n");
        scope.push(HashMap::new());
        self.generate_statement(source, then_branch, indent + 1, scope)?;
        scope.pop();
        source.push_str(&format!("{}}}", indent_str));

        match else_branch {
            None => source.push('\n'),
            Some(Statement::If { condition, then_branch, else_branch, .. }) => {
                source.push_str(" else ");
                self.generate_if_chain(source, condition, then_branch, else_branch.as_deref(), indent, scope, false)?;
            }
            Some(other) => {
                source.push_str(" else {\n");
                scope.push(HashMap::new());
                self.generate_statement(source, other, indent + 1, scope)?;
                scope.pop();
                source.push_str(&format!("{}}}\n", indent_str));
            }
        }

        Ok(())
    }

    fn generate_println_args(&self, source: &mut String, arguments: &[Expression], scope: &Scope) -> Result<()> {
        if arguments.is_empty() {
            return Ok(());
        }
        if arguments.len() == 1 {
            return self.generate_expression(source, &arguments[0], scope);
        }
        // println with several arguments concatenates them, so
        // `println(a, b)` behaves like `println(a + b)`.
        source.push('(');
        for (i, arg) in arguments.iter().enumerate() {
            if i > 0 {
                source.push_str(" + ");
            }
            self.generate_expression(source, arg, scope)?;
        }
        source.push(')');
        Ok(())
    }

    /// Infers the Java type an expression will evaluate to, using tracked
    /// local/parameter types instead of guessing from variable names.
    fn infer_type(&self, expr: &Expression, scope: &Scope) -> String {
        match expr {
            Expression::Number { .. } => "int".to_string(),
            Expression::String { .. } => "String".to_string(),
            Expression::Boolean { .. } => "boolean".to_string(),
            Expression::Null { .. } => OBJECT_TYPE.to_string(),
            Expression::Identifier { name, .. } => {
                for frame in scope.iter().rev() {
                    if let Some(t) = frame.get(name) {
                        return t.clone();
                    }
                }
                OBJECT_TYPE.to_string()
            }
            Expression::Unary { operand, .. } => self.infer_type(operand, scope),
            Expression::Binary { left, operator, right, .. } => {
                let left_type = self.infer_type(left, scope);
                let right_type = self.infer_type(right, scope);

                match operator {
                    BinaryOperator::Add => {
                        if left_type == "String" || right_type == "String" {
                            "String".to_string()
                        } else if left_type == "int" && right_type == "int" {
                            "int".to_string()
                        } else {
                            // One side is some Object-typed/unknown value;
                            // Java's `+` between an Object and anything
                            // else always means string concatenation, so
                            // this is the only type that's always valid.
                            "String".to_string()
                        }
                    }
                    BinaryOperator::Subtract | BinaryOperator::Multiply | BinaryOperator::Divide => "int".to_string(),
                    BinaryOperator::Equal | BinaryOperator::NotEqual |
                    BinaryOperator::LessThan | BinaryOperator::GreaterThan |
                    BinaryOperator::LessEqual | BinaryOperator::GreaterEqual |
                    BinaryOperator::And | BinaryOperator::Or => "boolean".to_string(),
                }
            }
            Expression::Call { function, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    if name == "println" {
                        return "void".to_string();
                    }
                    if let Some(ret) = intrinsic_return_type(name) {
                        return ret.to_string();
                    }
                    if let Some((_, ret)) = self.functions.get(name) {
                        return ret.clone();
                    }
                }
                OBJECT_TYPE.to_string()
            }
        }
    }

    fn generate_expression(&self, source: &mut String, expr: &Expression, scope: &Scope) -> Result<()> {
        match expr {
            Expression::String { value, .. } => {
                let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
                source.push_str(&format!("\"{}\"", escaped));
            }
            Expression::Number { value, .. } => {
                source.push_str(value);
            }
            Expression::Identifier { name, .. } => {
                source.push_str(name);
            }
            Expression::Boolean { value, .. } => {
                source.push_str(&format!("{}", value));
            }
            Expression::Null { .. } => {
                source.push_str("null");
            }
            Expression::Call { function, arguments, .. } => {
                if let Expression::Identifier { name, .. } = function.as_ref() {
                    self.generate_call(source, name, arguments, scope)?;
                }
            }
            Expression::Binary { left, operator, right, .. } => {
                let left_type = self.infer_type(left, scope);
                let right_type = self.infer_type(right, scope);
                let is_primitive = |t: &str| t == "int" || t == "boolean";

                let use_equals_method = matches!(operator, BinaryOperator::Equal | BinaryOperator::NotEqual)
                    && (!is_primitive(&left_type) || !is_primitive(&right_type));

                if use_equals_method {
                    // Java's `==`/`!=` on a non-primitive type is
                    // reference identity, not content equality -- two
                    // distinct String objects with identical content
                    // (e.g. the result of runtime concatenation vs. a
                    // literal) would silently compare unequal. Route
                    // through Objects.equals instead, which is
                    // content-based and null-safe.
                    if matches!(operator, BinaryOperator::NotEqual) {
                        source.push('!');
                    }
                    source.push_str("java.util.Objects.equals(");
                    self.generate_expression(source, left, scope)?;
                    source.push_str(", ");
                    self.generate_expression(source, right, scope)?;
                    source.push(')');
                } else {
                    let is_string_concat = matches!(operator, BinaryOperator::Add)
                        && (left_type == "String" || right_type == "String");

                    source.push('(');
                    self.generate_expression(source, left, scope)?;
                    if is_string_concat {
                        source.push_str(" + ");
                    } else {
                        let op = match operator {
                            BinaryOperator::Add => " + ",
                            BinaryOperator::Subtract => " - ",
                            BinaryOperator::Multiply => " * ",
                            BinaryOperator::Divide => " / ",
                            BinaryOperator::Equal => " == ",
                            BinaryOperator::NotEqual => " != ",
                            BinaryOperator::LessThan => " < ",
                            BinaryOperator::GreaterThan => " > ",
                            BinaryOperator::LessEqual => " <= ",
                            BinaryOperator::GreaterEqual => " >= ",
                            BinaryOperator::And => " && ",
                            BinaryOperator::Or => " || ",
                        };
                        source.push_str(op);
                    }
                    self.generate_expression(source, right, scope)?;
                    source.push(')');
                }
            }
            Expression::Unary { operator, operand, .. } => {
                let op = match operator {
                    UnaryOperator::Negate => "-",
                    UnaryOperator::Not => "!",
                };
                source.push_str(op);
                self.generate_expression(source, operand, scope)?;
            }
        }

        Ok(())
    }

    /// Generates a call, rewriting Core (string/math) intrinsics to real
    /// JVM standard-library calls, since Roze has no method-call syntax of
    /// its own yet to express `s.length()` directly.
    fn generate_call(&self, source: &mut String, name: &str, arguments: &[Expression], scope: &Scope) -> Result<()> {
        match name {
            "string_length" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).length()");
            }
            "string_to_upper" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).toUpperCase()");
            }
            "string_to_lower" if arguments.len() == 1 => {
                source.push_str("((String)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(")).toLowerCase()");
            }
            "string_concat" if arguments.len() == 2 => {
                source.push('(');
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(" + ");
                self.generate_expression(source, &arguments[1], scope)?;
                source.push(')');
            }
            "abs" if arguments.len() == 1 => {
                source.push_str("Math.abs(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push(')');
            }
            "max" if arguments.len() == 2 => {
                source.push_str("Math.max(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push_str(", ");
                self.generate_int_arg(source, &arguments[1], scope)?;
                source.push(')');
            }
            "min" if arguments.len() == 2 => {
                source.push_str("Math.min(");
                self.generate_int_arg(source, &arguments[0], scope)?;
                source.push_str(", ");
                self.generate_int_arg(source, &arguments[1], scope)?;
                source.push(')');
            }
            "to_string" if arguments.len() == 1 => {
                source.push_str("String.valueOf(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push(')');
            }
            "to_int" if arguments.len() == 1 => {
                source.push_str("Integer.parseInt(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push(')');
            }
            "is_number" if arguments.len() == 1 => {
                source.push_str("((Object)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(") instanceof Integer)");
            }
            "is_string" if arguments.len() == 1 => {
                source.push_str("((Object)(");
                self.generate_expression(source, &arguments[0], scope)?;
                source.push_str(") instanceof String)");
            }
            "println" => {
                source.push_str("System.out.println(");
                self.generate_println_args(source, arguments, scope)?;
                source.push(')');
            }
            _ => {
                source.push_str(name);
                source.push('(');
                for (i, arg) in arguments.iter().enumerate() {
                    if i > 0 {
                        source.push_str(", ");
                    }
                    self.generate_expression(source, arg, scope)?;
                }
                source.push(')');
            }
        }
        Ok(())
    }

    /// Generates an expression known to be used in an `int`-typed position
    /// (a Math.* argument). If the expression's static type isn't already
    /// `int`, it's coming from an Object-typed (untyped-parameter) value,
    /// so we unbox it via Integer -- valid whenever the runtime value
    /// really is a boxed Integer, matching the declared `int` parameter.
    fn generate_int_arg(&self, source: &mut String, expr: &Expression, scope: &Scope) -> Result<()> {
        let t = self.infer_type(expr, scope);
        if t == "int" {
            self.generate_expression(source, expr, scope)
        } else {
            source.push_str("((Integer)(Object)(");
            self.generate_expression(source, expr, scope)?;
            source.push_str("))");
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::tokenize;
    use crate::parser::parse;

    fn generate(src: &str) -> String {
        let program = parse(tokenize(src)).expect("fixture should parse");
        JavaSourceGenerator::new(program, "Fixture".to_string())
            .generate()
            .expect("fixture should generate")
    }

    #[test]
    fn emits_every_function_not_just_main() {
        let java = generate("func greet() { println(\"hi\"); } func main() { greet(); }");
        assert!(java.contains("static void greet"), "greet() should be emitted:\n{}", java);
        assert!(java.contains("static void main"), "main() should be emitted:\n{}", java);
        assert!(java.contains("greet();"), "main() should call greet():\n{}", java);
    }

    #[test]
    fn uses_declared_types_not_name_guessing() {
        // Previously, codegen guessed a variable's Java type from its
        // *name* (only x/y/z/i/j/k were ever treated as int). A variable
        // holding a string, named like one of those letters, must still
        // come out as String.
        let java = generate("func main() { let x = \"hello\"; println(x); }");
        assert!(java.contains("String x ="), "expected 'String x =', got:\n{}", java);
    }

    #[test]
    fn if_else_if_chain_generates_valid_shape() {
        let java = generate("func f(x: int) -> int { if x > 0 { return 1; } else if x < 0 { return -1; } else { return 0; } } func main() { }");
        assert!(java.contains("if (") && java.contains("} else if (") && java.contains("} else {"), "unexpected if/else shape:\n{}", java);
    }

    #[test]
    fn while_loop_generates_java_while() {
        let java = generate("func main() { let i = 0; while i < 3 { i = i + 1; } }");
        assert!(java.contains("while ("), "expected a while loop:\n{}", java);
    }

    #[test]
    fn for_loop_generates_java_for() {
        let java = generate("func main() { for let i = 0; i < 3; i = i + 1 { println(i); } }");
        assert!(java.contains("for (int i = 0;"), "expected a Java for-loop header:\n{}", java);
    }

    #[test]
    fn string_intrinsics_map_to_real_java_calls() {
        let java = generate("func main() { println(string_to_upper(\"hi\")); println(string_length(\"hi\")); }");
        assert!(java.contains(".toUpperCase()"), "expected toUpperCase():\n{}", java);
        assert!(java.contains(".length()"), "expected length():\n{}", java);
    }

    #[test]
    fn math_intrinsics_map_to_java_math() {
        let java = generate("func main() { println(abs(-5)); println(max(1, 2)); println(min(1, 2)); }");
        assert!(java.contains("Math.abs("));
        assert!(java.contains("Math.max("));
        assert!(java.contains("Math.min("));
    }

    #[test]
    fn intrinsic_named_function_is_never_emitted_as_a_real_method() {
        // Even if a program somehow declares its own `abs`, it must not
        // get emitted as a real Java method -- the call-site rewrite to
        // Math.abs() always takes priority.
        let java = generate("func abs(x: int) -> int { return x; } func main() { println(abs(-5)); }");
        assert!(!java.contains("static int abs"), "an 'abs' method should never be emitted:\n{}", java);
        assert!(java.contains("Math.abs("), "the call site should still use Math.abs():\n{}", java);
    }

    #[test]
    fn string_equality_compares_content_not_reference() {
        // Java's == on Strings is reference identity; a naive codegen
        // would emit `combined == "Hello World"` which silently gives the
        // wrong answer at runtime for a non-interned (e.g. runtime
        // concatenation) result. Must route through content equality.
        let java = generate("func main() { let a = \"Hello\"; let b = a + \"!\"; println(b == \"Hello!\"); }");
        assert!(java.contains("Objects.equals("), "expected content equality via Objects.equals:\n{}", java);
        assert!(!java.contains("== \"Hello!\""), "must not use reference equality (==) on strings:\n{}", java);
    }

    #[test]
    fn int_equality_still_uses_primitive_operator() {
        // No need to pay for Objects.equals boxing when both sides are
        // already primitives -- plain == is correct and cheaper.
        let java = generate("func main() { let a = 5; println(a == 5); }");
        assert!(java.contains("(a == 5)"), "expected plain == for int comparison:\n{}", java);
    }

    #[test]
    fn no_main_falls_back_to_placeholder() {
        let java = generate("func helper() { println(\"hi\"); }");
        assert!(java.contains("No main function found"));
    }
}
