// Generated by Roze compiler v0.1
public class core_demo {
    public static String classify(int x) {
        if ((x > 0)) {
            return "positive";
        } else if ((x < 0)) {
            return "negative";
        } else {
            return "zero";
        }
    }
    public static void countdown(int n) {
        int i = n;
        while ((i > 0)) {
            System.out.println(i);
            i = (i - 1);
        }
    }
    public static void main(String[] args) {
        String name = "Roze";
        System.out.println((("Hello, " + name) + "!"));
        System.out.println(((String)(name)).toUpperCase());
        System.out.println(((String)(name)).toLowerCase());
        System.out.println(((String)(name)).length());
        System.out.println(("foo" + "bar"));
        System.out.println(Math.abs(-42));
        System.out.println(Math.max(3, 9));
        System.out.println(Math.min(3, 9));
        System.out.println(String.valueOf(123));
        System.out.println((Integer.parseInt("456") + 1));
        System.out.println(((Object)(5) instanceof Integer));
        System.out.println(((Object)("hi") instanceof String));
        System.out.println(classify(10));
        System.out.println(classify(-5));
        System.out.println(classify(0));
        System.out.println("counting down:");
        countdown(3);
    }
}
