// Generated by Roze compiler v0.1
public class math {
    public static void main(String[] args) {
        int x = 10;
        int y = 20;
        int z = (x + y);
        System.out.println(("10 + 20 = " + z));
    }
}
