// Generated by Roze compiler v0.1
public class server_demo {
    public static void main(String[] args) {
        java.util.Map m = new java.util.HashMap();
        (m).put("hello", "world");
        System.out.println(__roze_json_encode(m));
        java.net.ServerSocket server = __roze_http_server_start(8080);
        System.out.println("listening on 8080");
        java.util.Map req = __roze_http_server_accept(server);
        __roze_http_server_respond(req, 200, "hi from roze");
        __roze_http_server_stop(server);
    }

    private static String __roze_read_file(String path) {
        try {
            return new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_write_file(String path, String content) {
        try {
            java.nio.file.Files.write(java.nio.file.Paths.get(path), content.getBytes());
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_append_file(String path, String content) {
        try {
            java.nio.file.Files.write(
                java.nio.file.Paths.get(path),
                content.getBytes(),
                java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.APPEND
            );
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static boolean __roze_delete_file(String path) {
        try {
            return java.nio.file.Files.deleteIfExists(java.nio.file.Paths.get(path));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static java.util.List __roze_read_lines(String path) {
        try {
            return new java.util.ArrayList(java.nio.file.Files.readAllLines(java.nio.file.Paths.get(path)));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static String __roze_http_get(String url) {
        try {
            java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();
            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(url))
                .GET()
                .build();
            java.net.http.HttpResponse<String> response = client.send(request, java.net.http.HttpResponse.BodyHandlers.ofString());
            return response.body();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }

    private static String __roze_http_post(String url, String body) {
        try {
            java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();
            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(url))
                .header("Content-Type", "application/json")
                .POST(java.net.http.HttpRequest.BodyPublishers.ofString(body))
                .build();
            java.net.http.HttpResponse<String> response = client.send(request, java.net.http.HttpResponse.BodyHandlers.ofString());
            return response.body();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }

    private static String __roze_json_encode(Object value) {
        StringBuilder sb = new StringBuilder();
        __roze_json_encode_value(value, sb);
        return sb.toString();
    }

    private static void __roze_json_encode_value(Object value, StringBuilder sb) {
        if (value == null) {
            sb.append("null");
        } else if (value instanceof String) {
            __roze_json_encode_string((String) value, sb);
        } else if (value instanceof Boolean || value instanceof Integer || value instanceof Long || value instanceof Double || value instanceof Float) {
            sb.append(value.toString());
        } else if (value instanceof java.util.List) {
            sb.append('[');
            java.util.List<?> list = (java.util.List<?>) value;
            for (int i = 0; i < list.size(); i++) {
                if (i > 0) sb.append(',');
                __roze_json_encode_value(list.get(i), sb);
            }
            sb.append(']');
        } else if (value instanceof java.util.Map) {
            sb.append('{');
            java.util.Map<?, ?> map = (java.util.Map<?, ?>) value;
            boolean first = true;
            for (java.util.Map.Entry<?, ?> entry : map.entrySet()) {
                if (!first) sb.append(',');
                first = false;
                __roze_json_encode_string(String.valueOf(entry.getKey()), sb);
                sb.append(':');
                __roze_json_encode_value(entry.getValue(), sb);
            }
            sb.append('}');
        } else {
            __roze_json_encode_string(value.toString(), sb);
        }
    }

    private static void __roze_json_encode_string(String s, StringBuilder sb) {
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '"') {
                sb.append("\\\"");
            } else if (c == '\\') {
                sb.append("\\\\");
            } else if (c == '\n') {
                sb.append("\\n");
            } else if (c == '\r') {
                sb.append("\\r");
            } else if (c == '\t') {
                sb.append("\\t");
            } else if (c < 0x20) {
                sb.append(String.format("\\u%04x", (int) c));
            } else {
                sb.append(c);
            }
        }
        sb.append('"');
    }

    private static Object __roze_json_decode(String json) {
        int[] pos = new int[]{0};
        return __roze_json_parse_value(json, pos);
    }

    private static void __roze_json_skip_ws(String s, int[] pos) {
        while (pos[0] < s.length() && Character.isWhitespace(s.charAt(pos[0]))) pos[0]++;
    }

    private static Object __roze_json_parse_value(String s, int[] pos) {
        __roze_json_skip_ws(s, pos);
        char c = s.charAt(pos[0]);
        if (c == '{') return __roze_json_parse_object(s, pos);
        if (c == '[') return __roze_json_parse_array(s, pos);
        if (c == '"') return __roze_json_parse_string(s, pos);
        if (c == 't') { pos[0] += 4; return Boolean.TRUE; }
        if (c == 'f') { pos[0] += 5; return Boolean.FALSE; }
        if (c == 'n') { pos[0] += 4; return null; }
        return __roze_json_parse_number(s, pos);
    }

    private static java.util.Map __roze_json_parse_object(String s, int[] pos) {
        java.util.Map<Object, Object> map = new java.util.HashMap<Object, Object>();
        pos[0]++;
        __roze_json_skip_ws(s, pos);
        if (s.charAt(pos[0]) == '}') { pos[0]++; return map; }
        while (true) {
            __roze_json_skip_ws(s, pos);
            String key = __roze_json_parse_string(s, pos);
            __roze_json_skip_ws(s, pos);
            pos[0]++;
            Object value = __roze_json_parse_value(s, pos);
            map.put(key, value);
            __roze_json_skip_ws(s, pos);
            char c = s.charAt(pos[0]);
            if (c == ',') { pos[0]++; continue; }
            if (c == '}') { pos[0]++; break; }
            throw new RuntimeException("Invalid JSON: expected ',' or '}' at position " + pos[0]);
        }
        return map;
    }

    private static java.util.List __roze_json_parse_array(String s, int[] pos) {
        java.util.List<Object> list = new java.util.ArrayList<Object>();
        pos[0]++;
        __roze_json_skip_ws(s, pos);
        if (s.charAt(pos[0]) == ']') { pos[0]++; return list; }
        while (true) {
            Object value = __roze_json_parse_value(s, pos);
            list.add(value);
            __roze_json_skip_ws(s, pos);
            char c = s.charAt(pos[0]);
            if (c == ',') { pos[0]++; continue; }
            if (c == ']') { pos[0]++; break; }
            throw new RuntimeException("Invalid JSON: expected ',' or ']' at position " + pos[0]);
        }
        return list;
    }

    private static String __roze_json_parse_string(String s, int[] pos) {
        pos[0]++;
        StringBuilder sb = new StringBuilder();
        while (s.charAt(pos[0]) != '"') {
            char c = s.charAt(pos[0]);
            if (c == '\\') {
                pos[0]++;
                char esc = s.charAt(pos[0]);
                if (esc == '"') sb.append('"');
                else if (esc == '\\') sb.append('\\');
                else if (esc == '/') sb.append('/');
                else if (esc == 'n') sb.append('\n');
                else if (esc == 't') sb.append('\t');
                else if (esc == 'r') sb.append('\r');
                else if (esc == 'b') sb.append('\b');
                else if (esc == 'f') sb.append('\f');
                else if (esc == 'u') {
                    String hex = s.substring(pos[0] + 1, pos[0] + 5);
                    sb.append((char) Integer.parseInt(hex, 16));
                    pos[0] += 4;
                } else {
                    sb.append(esc);
                }
                pos[0]++;
            } else {
                sb.append(c);
                pos[0]++;
            }
        }
        pos[0]++;
        return sb.toString();
    }

    private static Object __roze_json_parse_number(String s, int[] pos) {
        int start = pos[0];
        if (s.charAt(pos[0]) == '-') pos[0]++;
        while (pos[0] < s.length() && Character.isDigit(s.charAt(pos[0]))) pos[0]++;
        boolean isDouble = false;
        if (pos[0] < s.length() && s.charAt(pos[0]) == '.') {
            isDouble = true;
            pos[0]++;
            while (pos[0] < s.length() && Character.isDigit(s.charAt(pos[0]))) pos[0]++;
        }
        if (pos[0] < s.length() && (s.charAt(pos[0]) == 'e' || s.charAt(pos[0]) == 'E')) {
            isDouble = true;
            pos[0]++;
            if (pos[0] < s.length() && (s.charAt(pos[0]) == '+' || s.charAt(pos[0]) == '-')) pos[0]++;
            while (pos[0] < s.length() && Character.isDigit(s.charAt(pos[0]))) pos[0]++;
        }
        String numStr = s.substring(start, pos[0]);
        if (isDouble) {
            return Double.parseDouble(numStr);
        }
        try {
            return Integer.parseInt(numStr);
        } catch (NumberFormatException e) {
            return Long.parseLong(numStr);
        }
    }

    private static java.net.ServerSocket __roze_http_server_start(int port) {
        try {
            return new java.net.ServerSocket(port);
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static int __roze_find_header_end(byte[] data) {
        for (int i = 0; i + 3 < data.length; i++) {
            if (data[i] == '\r' && data[i + 1] == '\n' && data[i + 2] == '\r' && data[i + 3] == '\n') {
                return i;
            }
        }
        return -1;
    }

    private static java.util.Map __roze_http_server_accept(java.net.ServerSocket server) {
        try {
            java.net.Socket socket = server.accept();
            java.io.InputStream in = socket.getInputStream();
            java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
            byte[] chunk = new byte[8192];
            int headerEnd = -1;
            while (headerEnd < 0) {
                int n = in.read(chunk);
                if (n <= 0) break;
                buffer.write(chunk, 0, n);
                headerEnd = __roze_find_header_end(buffer.toByteArray());
            }
            byte[] all = buffer.toByteArray();
            String headerText = new String(all, 0, Math.max(headerEnd, 0), "UTF-8");
            String[] lines = headerText.split("\r\n");
            String[] requestLineParts = lines.length > 0 ? lines[0].split(" ") : new String[0];
            String method = requestLineParts.length > 0 ? requestLineParts[0] : "GET";
            String path = requestLineParts.length > 1 ? requestLineParts[1] : "/";

            int contentLength = 0;
            for (String line : lines) {
                if (line.toLowerCase().startsWith("content-length:")) {
                    contentLength = Integer.parseInt(line.substring(line.indexOf(':') + 1).trim());
                }
            }

            int bodyStart = headerEnd + 4;
            java.io.ByteArrayOutputStream bodyBuffer = new java.io.ByteArrayOutputStream();
            if (bodyStart < all.length) {
                bodyBuffer.write(all, bodyStart, all.length - bodyStart);
            }
            while (bodyBuffer.size() < contentLength) {
                int n = in.read(chunk);
                if (n <= 0) break;
                bodyBuffer.write(chunk, 0, n);
            }
            String body = bodyBuffer.toString("UTF-8");

            java.util.Map<Object, Object> request = new java.util.HashMap<Object, Object>();
            request.put("method", method);
            request.put("path", path);
            request.put("body", body);
            request.put("__socket", socket);
            return request;
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static String __roze_http_status_text(int status) {
        if (status == 200) return "OK";
        if (status == 201) return "Created";
        if (status == 204) return "No Content";
        if (status == 301) return "Moved Permanently";
        if (status == 302) return "Found";
        if (status == 400) return "Bad Request";
        if (status == 401) return "Unauthorized";
        if (status == 403) return "Forbidden";
        if (status == 404) return "Not Found";
        if (status == 500) return "Internal Server Error";
        return "Unknown";
    }

    private static void __roze_http_server_respond(java.util.Map request, int status, String body) {
        try {
            java.net.Socket socket = (java.net.Socket) request.get("__socket");
            byte[] bodyBytes = body.getBytes("UTF-8");
            String header = "HTTP/1.1 " + status + " " + __roze_http_status_text(status) + "\r\n"
                + "Content-Type: text/plain; charset=utf-8\r\n"
                + "Content-Length: " + bodyBytes.length + "\r\n"
                + "Connection: close\r\n\r\n";
            java.io.OutputStream out = socket.getOutputStream();
            out.write(header.getBytes("UTF-8"));
            out.write(bodyBytes);
            out.flush();
            socket.close();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_http_server_stop(java.net.ServerSocket server) {
        try {
            server.close();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static java.sql.Connection __roze_sql_connect(String url) {
        try {
            return java.sql.DriverManager.getConnection(url);
        } catch (java.sql.SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static java.util.List __roze_sql_query(java.sql.Connection conn, String sql) {
        try {
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            java.sql.ResultSetMetaData meta = rs.getMetaData();
            int columnCount = meta.getColumnCount();
            java.util.List<Object> rows = new java.util.ArrayList<Object>();
            while (rs.next()) {
                java.util.Map<Object, Object> row = new java.util.HashMap<Object, Object>();
                for (int i = 1; i <= columnCount; i++) {
                    row.put(meta.getColumnLabel(i), rs.getObject(i));
                }
                rows.add(row);
            }
            rs.close();
            stmt.close();
            return rows;
        } catch (java.sql.SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static int __roze_sql_execute(java.sql.Connection conn, String sql) {
        try {
            java.sql.Statement stmt = conn.createStatement();
            int affected = stmt.executeUpdate(sql);
            stmt.close();
            return affected;
        } catch (java.sql.SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_sql_close(java.sql.Connection conn) {
        try {
            conn.close();
        } catch (java.sql.SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
