// Generated by Roze compiler v0.1
public class test_phase1 {
    public static void main(String[] args) {
        int x = 10;
        int y = 20;
        int sum = (x + y);
        System.out.println(("10 + 20 = " + sum));
    }
}
