// Generated by Roze compiler v0.1
public class test {
    public static void main(String[] args) {
        java.util.List fruits = new java.util.ArrayList();
        (fruits).add("apple");
        (fruits).add("banana");
        for (int i = 0; (i < (fruits).size()); i = (i + 1)) {
            System.out.println((fruits).get(i));
        }
        __roze_write_file("notes.txt", "hello world");
        System.out.println(__roze_read_file("notes.txt"));
        __roze_delete_file("notes.txt");
        System.out.println(__roze_http_get("https://example.com"));
    }

    private static String __roze_read_file(String path) {
        try {
            return new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_write_file(String path, String content) {
        try {
            java.nio.file.Files.write(java.nio.file.Paths.get(path), content.getBytes());
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static void __roze_append_file(String path, String content) {
        try {
            java.nio.file.Files.write(
                java.nio.file.Paths.get(path),
                content.getBytes(),
                java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.APPEND
            );
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static boolean __roze_delete_file(String path) {
        try {
            return java.nio.file.Files.deleteIfExists(java.nio.file.Paths.get(path));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static java.util.List __roze_read_lines(String path) {
        try {
            return new java.util.ArrayList(java.nio.file.Files.readAllLines(java.nio.file.Paths.get(path)));
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static String __roze_http_get(String url) {
        try {
            java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();
            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(url))
                .GET()
                .build();
            java.net.http.HttpResponse<String> response = client.send(request, java.net.http.HttpResponse.BodyHandlers.ofString());
            return response.body();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }

    private static String __roze_http_post(String url, String body) {
        try {
            java.net.http.HttpClient client = java.net.http.HttpClient.newHttpClient();
            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder()
                .uri(java.net.URI.create(url))
                .header("Content-Type", "application/json")
                .POST(java.net.http.HttpRequest.BodyPublishers.ofString(body))
                .build();
            java.net.http.HttpResponse<String> response = client.send(request, java.net.http.HttpResponse.BodyHandlers.ofString());
            return response.body();
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }
}
