// Generated by Roze compiler v0.1
public class main {
    public static void main(String[] args) {
        String project_name = "test_project";
        String author = "Firoze";
        System.out.println((("🌹 Hello from " + project_name) + "!"));
        System.out.println("Welcome to Roze programming language!");
        System.out.println(("Created by " + author));
        String message = "This project was created with `roze new`";
        System.out.println(message);
    }
}
