[package]
name = "roze-compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "roze"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
colored = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
which = "6.0"
cranelift = "0.134"
cranelift-module = "0.134"
cranelift-object = "0.134"
cranelift-native = "0.134"
target-lexicon = "0.12"

[lib]
path = "src/lib.rs"