// src/dependency.rs
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use anyhow::{Result, anyhow};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Dependency {
    pub name: String,
    pub version: String,
    pub source: DependencySource,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum DependencySource {
    Registry(String),
    Path(String),
    Git { url: String, tag: Option<String> },
}

pub struct DependencyManager {
    pub dependencies: HashMap<String, Dependency>,
    pub project_dir: PathBuf,
}

impl DependencyManager {
    pub fn new(project_dir: PathBuf) -> Self {
        Self {
            dependencies: HashMap::new(),
            project_dir,
        }
    }

    pub fn add_dependency(&mut self, name: &str, version: &str) -> Result<()> {
        let (package, version) = if name.contains("::") {
            let parts: Vec<&str> = name.split("::").collect();
            (parts[1].to_string(), version.to_string())
        } else {
            (name.to_string(), version.to_string())
        };

        let dep = Dependency {
            name: package.clone(),
            version: version.clone(),
            source: DependencySource::Registry("https://registry.roze.dev".to_string()),
        };

        self.dependencies.insert(package, dep);
        self.save_manifest()?;
        Ok(())
    }

    pub fn remove_dependency(&mut self, name: &str) -> Result<()> {
        let package = if name.contains("::") {
            let parts: Vec<&str> = name.split("::").collect();
            parts[1].to_string()
        } else {
            name.to_string()
        };

        if self.dependencies.remove(&package).is_none() {
            return Err(anyhow!("Dependency '{}' not found", name));
        }
        self.save_manifest()?;
        Ok(())
    }

    pub fn save_manifest(&self) -> Result<()> {
        let manifest_path = self.project_dir.join("roze.toml");
        if manifest_path.exists() {
            let content = fs::read_to_string(&manifest_path)?;
            let mut config: toml::Value = toml::from_str(&content)?;

            // Ensure dependencies section exists
            if !config.is_table() {
                config = toml::Value::Table(toml::map::Map::new());
            }

            // Always ensure dependencies is a table
            if !config.get("dependencies").is_some() {
                config.as_table_mut().unwrap().insert(
                    "dependencies".to_string(),
                    toml::Value::Table(toml::map::Map::new())
                );
            }

            let deps = self.dependencies.values().map(|dep| {
                (dep.name.clone(), toml::Value::String(dep.version.clone()))
            }).collect::<toml::map::Map<String, toml::Value>>();

            config["dependencies"] = toml::Value::Table(deps);
            fs::write(&manifest_path, toml::to_string_pretty(&config)?)?;
        }
        Ok(())
    }

    pub fn install_all(&self) -> Result<()> {
        println!("📦 Installing dependencies...");

        if self.dependencies.is_empty() {
            println!("  No dependencies to install");
            return Ok(());
        }

        for dep in self.dependencies.values() {
            println!("  Installing {} v{}", dep.name, dep.version);

            let dep_dir = self.project_dir.join("libs").join(&dep.name);
            fs::create_dir_all(&dep_dir)?;

            let stub = format!(
                r#"// Library: {}
// Version: {}
// Auto-generated by Roze package manager

func {}_version() -> string {{
    return "{}";
}}
"#,
                dep.name, dep.version, dep.name, dep.version
            );

            fs::write(dep_dir.join("lib.roze"), stub)?;
        }

        println!("✅ All dependencies installed!");
        Ok(())
    }
}